{
 "title": "Advertising Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Income per day",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH \nclicks_stats AS (\n    SELECT \n        day,\n        count(DISTINCT client_id) as click_count,\n        sum(income) as income_sum\n    FROM advertising.ad_clicks\n    GROUP BY day\n),\nimpression_stats AS (\n    SELECT \n        day,\n        count(DISTINCT client_id) as impression_count\n    FROM advertising.ad_impressions\n    GROUP BY day\n),\nlast_days AS (\n    SELECT \n        c.day,\n        c.click_count,\n        c.income_sum,\n        COALESCE(i.impression_count, 0) as impression_count\n    FROM clicks_stats c\n    LEFT JOIN impression_stats i ON c.day = i.day\n    ORDER BY c.day DESC\n    LIMIT 30\n)\nSELECT * FROM last_days\nORDER BY day ASC"
    }
   ]
  },
  {
   "title": "Clicks count per day",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH last_days AS (\n    SELECT DISTINCT day\n    FROM advertising.ad_clicks\n    ORDER BY day DESC\n    LIMIT 100\n)\nSELECT \n    ac.day,\n    count(ac.campaign_id) as clicks_count\nFROM advertising.ad_clicks ac\nINNER JOIN last_days ld ON ac.day = ld.day\nGROUP BY ac.day, ac.campaign_id\nORDER BY ac.day ASC"
    }
   ]
  },
  {
   "title": "Impressions count per day",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH last_days AS (\n    SELECT DISTINCT day\n    FROM advertising.ad_impressions\n    ORDER BY day DESC\n    LIMIT 100\n)\nSELECT \n    ai.day,\n    count(ai.campaign_id) as impressions_count\nFROM advertising.ad_impressions ai\nINNER JOIN last_days ld ON ai.day = ld.day\nGROUP BY ai.day, ai.campaign_id\nORDER BY ai.day ASC"
    }
   ]
  }
 ]
}