// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Advertiser is the predicate function for advertiser builders.
type Advertiser func(*sql.Selector)

// Campaign is the predicate function for campaign builders.
type Campaign func(*sql.Selector)

// MlScore is the predicate function for mlscore builders.
type MlScore func(*sql.Selector)

// Targeting is the predicate function for targeting builders.
type Targeting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
