apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:9000
    jsonData:
      defaultDatabase: advertising
      port: 9000
      server: clickhouse
      username: default
    secureJsonData:
      password: password
    editable: true
    isDefault: true
