// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdvertisersColumns holds the columns for the "advertisers" table.
	AdvertisersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
	}
	// AdvertisersTable holds the schema information for the "advertisers" table.
	AdvertisersTable = &schema.Table{
		Name:       "advertisers",
		Columns:    AdvertisersColumns,
		PrimaryKey: []*schema.Column{AdvertisersColumns[0]},
	}
	// CampaignsColumns holds the columns for the "campaigns" table.
	CampaignsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "advertiser_id", Type: field.TypeUUID},
		{Name: "impressions_limit", Type: field.TypeInt},
		{Name: "clicks_limit", Type: field.TypeInt},
		{Name: "cost_per_impression", Type: field.TypeFloat64},
		{Name: "cost_per_click", Type: field.TypeFloat64},
		{Name: "ad_title", Type: field.TypeString},
		{Name: "ad_text", Type: field.TypeString},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "start_date", Type: field.TypeInt},
		{Name: "end_date", Type: field.TypeInt},
		{Name: "moderated", Type: field.TypeBool},
	}
	// CampaignsTable holds the schema information for the "campaigns" table.
	CampaignsTable = &schema.Table{
		Name:       "campaigns",
		Columns:    CampaignsColumns,
		PrimaryKey: []*schema.Column{CampaignsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "campaign_start_date_end_date",
				Unique:  false,
				Columns: []*schema.Column{CampaignsColumns[9], CampaignsColumns[10]},
			},
		},
	}
	// MlScoresColumns holds the columns for the "ml_scores" table.
	MlScoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "score", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "advertiser_id", Type: field.TypeUUID},
	}
	// MlScoresTable holds the schema information for the "ml_scores" table.
	MlScoresTable = &schema.Table{
		Name:       "ml_scores",
		Columns:    MlScoresColumns,
		PrimaryKey: []*schema.Column{MlScoresColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ml_scores_users_user",
				Columns:    []*schema.Column{MlScoresColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "ml_scores_advertisers_advertiser",
				Columns:    []*schema.Column{MlScoresColumns[3]},
				RefColumns: []*schema.Column{AdvertisersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mlscore_user_id_advertiser_id",
				Unique:  true,
				Columns: []*schema.Column{MlScoresColumns[2], MlScoresColumns[3]},
			},
		},
	}
	// TargetingsColumns holds the columns for the "targetings" table.
	TargetingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "gender", Type: field.TypeEnum, Nullable: true, Enums: []string{"MALE", "FEMALE", "ALL"}},
		{Name: "age_from", Type: field.TypeInt, Nullable: true},
		{Name: "age_to", Type: field.TypeInt, Nullable: true},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "campaign_targeting", Type: field.TypeUUID, Unique: true},
	}
	// TargetingsTable holds the schema information for the "targetings" table.
	TargetingsTable = &schema.Table{
		Name:       "targetings",
		Columns:    TargetingsColumns,
		PrimaryKey: []*schema.Column{TargetingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "targetings_campaigns_targeting",
				Columns:    []*schema.Column{TargetingsColumns[5]},
				RefColumns: []*schema.Column{CampaignsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "targeting_location_campaign_targeting",
				Unique:  false,
				Columns: []*schema.Column{TargetingsColumns[4], TargetingsColumns[5]},
			},
			{
				Name:    "targeting_age_from_age_to_campaign_targeting",
				Unique:  false,
				Columns: []*schema.Column{TargetingsColumns[2], TargetingsColumns[3], TargetingsColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "login", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt, Nullable: true},
		{Name: "location", Type: field.TypeString, Nullable: true},
		{Name: "gender", Type: field.TypeEnum, Nullable: true, Enums: []string{"MALE", "FEMALE"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdvertisersTable,
		CampaignsTable,
		MlScoresTable,
		TargetingsTable,
		UsersTable,
	}
)

func init() {
	MlScoresTable.ForeignKeys[0].RefTable = UsersTable
	MlScoresTable.ForeignKeys[1].RefTable = AdvertisersTable
	TargetingsTable.ForeignKeys[0].RefTable = CampaignsTable
}
