// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nlypage-final/internal/adapters/database/postgres/ent/advertiser"
	"nlypage-final/internal/adapters/database/postgres/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdvertiserUpdate is the builder for updating Advertiser entities.
type AdvertiserUpdate struct {
	config
	hooks    []Hook
	mutation *AdvertiserMutation
}

// Where appends a list predicates to the AdvertiserUpdate builder.
func (au *AdvertiserUpdate) Where(ps ...predicate.Advertiser) *AdvertiserUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AdvertiserUpdate) SetName(s string) *AdvertiserUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AdvertiserUpdate) SetNillableName(s *string) *AdvertiserUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// Mutation returns the AdvertiserMutation object of the builder.
func (au *AdvertiserUpdate) Mutation() *AdvertiserMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AdvertiserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AdvertiserUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AdvertiserUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AdvertiserUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AdvertiserUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := advertiser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Advertiser.name": %w`, err)}
		}
	}
	return nil
}

func (au *AdvertiserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(advertiser.Table, advertiser.Columns, sqlgraph.NewFieldSpec(advertiser.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(advertiser.FieldName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{advertiser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AdvertiserUpdateOne is the builder for updating a single Advertiser entity.
type AdvertiserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdvertiserMutation
}

// SetName sets the "name" field.
func (auo *AdvertiserUpdateOne) SetName(s string) *AdvertiserUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AdvertiserUpdateOne) SetNillableName(s *string) *AdvertiserUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// Mutation returns the AdvertiserMutation object of the builder.
func (auo *AdvertiserUpdateOne) Mutation() *AdvertiserMutation {
	return auo.mutation
}

// Where appends a list predicates to the AdvertiserUpdate builder.
func (auo *AdvertiserUpdateOne) Where(ps ...predicate.Advertiser) *AdvertiserUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AdvertiserUpdateOne) Select(field string, fields ...string) *AdvertiserUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Advertiser entity.
func (auo *AdvertiserUpdateOne) Save(ctx context.Context) (*Advertiser, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AdvertiserUpdateOne) SaveX(ctx context.Context) *Advertiser {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AdvertiserUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AdvertiserUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AdvertiserUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := advertiser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Advertiser.name": %w`, err)}
		}
	}
	return nil
}

func (auo *AdvertiserUpdateOne) sqlSave(ctx context.Context) (_node *Advertiser, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(advertiser.Table, advertiser.Columns, sqlgraph.NewFieldSpec(advertiser.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Advertiser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, advertiser.FieldID)
		for _, f := range fields {
			if !advertiser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != advertiser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(advertiser.FieldName, field.TypeString, value)
	}
	_node = &Advertiser{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{advertiser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
