// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"nlypage-final/internal/adapters/database/postgres/ent/advertiser"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Advertiser is the model entity for the Advertiser schema.
type Advertiser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name         string `json:"name,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Advertiser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case advertiser.FieldName:
			values[i] = new(sql.NullString)
		case advertiser.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Advertiser fields.
func (a *Advertiser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case advertiser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				a.ID = *value
			}
		case advertiser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				a.Name = value.String
			}
		default:
			a.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Advertiser.
// This includes values selected through modifiers, order, etc.
func (a *Advertiser) Value(name string) (ent.Value, error) {
	return a.selectValues.Get(name)
}

// Update returns a builder for updating this Advertiser.
// Note that you need to call Advertiser.Unwrap() before calling this method if this Advertiser
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Advertiser) Update() *AdvertiserUpdateOne {
	return NewAdvertiserClient(a.config).UpdateOne(a)
}

// Unwrap unwraps the Advertiser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (a *Advertiser) Unwrap() *Advertiser {
	_tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Advertiser is not a transactional entity")
	}
	a.config.driver = _tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Advertiser) String() string {
	var builder strings.Builder
	builder.WriteString("Advertiser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", a.ID))
	builder.WriteString("name=")
	builder.WriteString(a.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Advertisers is a parsable slice of Advertiser.
type Advertisers []*Advertiser
