// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"nlypage-final/internal/adapters/database/postgres/ent/advertiser"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AdvertiserCreate is the builder for creating a Advertiser entity.
type AdvertiserCreate struct {
	config
	mutation *AdvertiserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (ac *AdvertiserCreate) SetName(s string) *AdvertiserCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AdvertiserCreate) SetID(u uuid.UUID) *AdvertiserCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *AdvertiserCreate) SetNillableID(u *uuid.UUID) *AdvertiserCreate {
	if u != nil {
		ac.SetID(*u)
	}
	return ac
}

// Mutation returns the AdvertiserMutation object of the builder.
func (ac *AdvertiserCreate) Mutation() *AdvertiserMutation {
	return ac.mutation
}

// Save creates the Advertiser in the database.
func (ac *AdvertiserCreate) Save(ctx context.Context) (*Advertiser, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AdvertiserCreate) SaveX(ctx context.Context) *Advertiser {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AdvertiserCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AdvertiserCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AdvertiserCreate) defaults() {
	if _, ok := ac.mutation.ID(); !ok {
		v := advertiser.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AdvertiserCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Advertiser.name"`)}
	}
	if v, ok := ac.mutation.Name(); ok {
		if err := advertiser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Advertiser.name": %w`, err)}
		}
	}
	return nil
}

func (ac *AdvertiserCreate) sqlSave(ctx context.Context) (*Advertiser, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AdvertiserCreate) createSpec() (*Advertiser, *sqlgraph.CreateSpec) {
	var (
		_node = &Advertiser{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(advertiser.Table, sqlgraph.NewFieldSpec(advertiser.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = ac.conflict
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.SetField(advertiser.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Advertiser.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdvertiserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ac *AdvertiserCreate) OnConflict(opts ...sql.ConflictOption) *AdvertiserUpsertOne {
	ac.conflict = opts
	return &AdvertiserUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AdvertiserCreate) OnConflictColumns(columns ...string) *AdvertiserUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AdvertiserUpsertOne{
		create: ac,
	}
}

type (
	// AdvertiserUpsertOne is the builder for "upsert"-ing
	//  one Advertiser node.
	AdvertiserUpsertOne struct {
		create *AdvertiserCreate
	}

	// AdvertiserUpsert is the "OnConflict" setter.
	AdvertiserUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AdvertiserUpsert) SetName(v string) *AdvertiserUpsert {
	u.Set(advertiser.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AdvertiserUpsert) UpdateName() *AdvertiserUpsert {
	u.SetExcluded(advertiser.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(advertiser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AdvertiserUpsertOne) UpdateNewValues() *AdvertiserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(advertiser.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AdvertiserUpsertOne) Ignore() *AdvertiserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdvertiserUpsertOne) DoNothing() *AdvertiserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdvertiserCreate.OnConflict
// documentation for more info.
func (u *AdvertiserUpsertOne) Update(set func(*AdvertiserUpsert)) *AdvertiserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdvertiserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AdvertiserUpsertOne) SetName(v string) *AdvertiserUpsertOne {
	return u.Update(func(s *AdvertiserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AdvertiserUpsertOne) UpdateName() *AdvertiserUpsertOne {
	return u.Update(func(s *AdvertiserUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *AdvertiserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdvertiserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdvertiserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AdvertiserUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AdvertiserUpsertOne.ID is not supported by MySQL driver. Use AdvertiserUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AdvertiserUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AdvertiserCreateBulk is the builder for creating many Advertiser entities in bulk.
type AdvertiserCreateBulk struct {
	config
	err      error
	builders []*AdvertiserCreate
	conflict []sql.ConflictOption
}

// Save creates the Advertiser entities in the database.
func (acb *AdvertiserCreateBulk) Save(ctx context.Context) ([]*Advertiser, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Advertiser, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdvertiserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AdvertiserCreateBulk) SaveX(ctx context.Context) []*Advertiser {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AdvertiserCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AdvertiserCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Advertiser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AdvertiserUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (acb *AdvertiserCreateBulk) OnConflict(opts ...sql.ConflictOption) *AdvertiserUpsertBulk {
	acb.conflict = opts
	return &AdvertiserUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AdvertiserCreateBulk) OnConflictColumns(columns ...string) *AdvertiserUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AdvertiserUpsertBulk{
		create: acb,
	}
}

// AdvertiserUpsertBulk is the builder for "upsert"-ing
// a bulk of Advertiser nodes.
type AdvertiserUpsertBulk struct {
	create *AdvertiserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(advertiser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AdvertiserUpsertBulk) UpdateNewValues() *AdvertiserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(advertiser.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Advertiser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AdvertiserUpsertBulk) Ignore() *AdvertiserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AdvertiserUpsertBulk) DoNothing() *AdvertiserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AdvertiserCreateBulk.OnConflict
// documentation for more info.
func (u *AdvertiserUpsertBulk) Update(set func(*AdvertiserUpsert)) *AdvertiserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AdvertiserUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AdvertiserUpsertBulk) SetName(v string) *AdvertiserUpsertBulk {
	return u.Update(func(s *AdvertiserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AdvertiserUpsertBulk) UpdateName() *AdvertiserUpsertBulk {
	return u.Update(func(s *AdvertiserUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *AdvertiserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AdvertiserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AdvertiserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AdvertiserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
