// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"nlypage-final/internal/adapters/database/postgres/ent/advertiser"
	"nlypage-final/internal/adapters/database/postgres/ent/mlscore"
	"nlypage-final/internal/adapters/database/postgres/ent/predicate"
	"nlypage-final/internal/adapters/database/postgres/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MlScoreQuery is the builder for querying MlScore entities.
type MlScoreQuery struct {
	config
	ctx            *QueryContext
	order          []mlscore.OrderOption
	inters         []Interceptor
	predicates     []predicate.MlScore
	withUser       *UserQuery
	withAdvertiser *AdvertiserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MlScoreQuery builder.
func (msq *MlScoreQuery) Where(ps ...predicate.MlScore) *MlScoreQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit the number of records to be returned by this query.
func (msq *MlScoreQuery) Limit(limit int) *MlScoreQuery {
	msq.ctx.Limit = &limit
	return msq
}

// Offset to start from.
func (msq *MlScoreQuery) Offset(offset int) *MlScoreQuery {
	msq.ctx.Offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MlScoreQuery) Unique(unique bool) *MlScoreQuery {
	msq.ctx.Unique = &unique
	return msq
}

// Order specifies how the records should be ordered.
func (msq *MlScoreQuery) Order(o ...mlscore.OrderOption) *MlScoreQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// QueryUser chains the current query on the "user" edge.
func (msq *MlScoreQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: msq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := msq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mlscore.Table, mlscore.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, mlscore.UserTable, mlscore.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(msq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdvertiser chains the current query on the "advertiser" edge.
func (msq *MlScoreQuery) QueryAdvertiser() *AdvertiserQuery {
	query := (&AdvertiserClient{config: msq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := msq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mlscore.Table, mlscore.FieldID, selector),
			sqlgraph.To(advertiser.Table, advertiser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, mlscore.AdvertiserTable, mlscore.AdvertiserColumn),
		)
		fromU = sqlgraph.SetNeighbors(msq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MlScore entity from the query.
// Returns a *NotFoundError when no MlScore was found.
func (msq *MlScoreQuery) First(ctx context.Context) (*MlScore, error) {
	nodes, err := msq.Limit(1).All(setContextOp(ctx, msq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mlscore.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MlScoreQuery) FirstX(ctx context.Context) *MlScore {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MlScore ID from the query.
// Returns a *NotFoundError when no MlScore ID was found.
func (msq *MlScoreQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(setContextOp(ctx, msq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mlscore.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MlScoreQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MlScore entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MlScore entity is found.
// Returns a *NotFoundError when no MlScore entities are found.
func (msq *MlScoreQuery) Only(ctx context.Context) (*MlScore, error) {
	nodes, err := msq.Limit(2).All(setContextOp(ctx, msq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mlscore.Label}
	default:
		return nil, &NotSingularError{mlscore.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MlScoreQuery) OnlyX(ctx context.Context) *MlScore {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MlScore ID in the query.
// Returns a *NotSingularError when more than one MlScore ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MlScoreQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(setContextOp(ctx, msq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mlscore.Label}
	default:
		err = &NotSingularError{mlscore.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MlScoreQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MlScores.
func (msq *MlScoreQuery) All(ctx context.Context) ([]*MlScore, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryAll)
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MlScore, *MlScoreQuery]()
	return withInterceptors[[]*MlScore](ctx, msq, qr, msq.inters)
}

// AllX is like All, but panics if an error occurs.
func (msq *MlScoreQuery) AllX(ctx context.Context) []*MlScore {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MlScore IDs.
func (msq *MlScoreQuery) IDs(ctx context.Context) (ids []int, err error) {
	if msq.ctx.Unique == nil && msq.path != nil {
		msq.Unique(true)
	}
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryIDs)
	if err = msq.Select(mlscore.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MlScoreQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MlScoreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryCount)
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, msq, querierCount[*MlScoreQuery](), msq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MlScoreQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MlScoreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryExist)
	switch _, err := msq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MlScoreQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MlScoreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MlScoreQuery) Clone() *MlScoreQuery {
	if msq == nil {
		return nil
	}
	return &MlScoreQuery{
		config:         msq.config,
		ctx:            msq.ctx.Clone(),
		order:          append([]mlscore.OrderOption{}, msq.order...),
		inters:         append([]Interceptor{}, msq.inters...),
		predicates:     append([]predicate.MlScore{}, msq.predicates...),
		withUser:       msq.withUser.Clone(),
		withAdvertiser: msq.withAdvertiser.Clone(),
		// clone intermediate query.
		sql:  msq.sql.Clone(),
		path: msq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (msq *MlScoreQuery) WithUser(opts ...func(*UserQuery)) *MlScoreQuery {
	query := (&UserClient{config: msq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	msq.withUser = query
	return msq
}

// WithAdvertiser tells the query-builder to eager-load the nodes that are connected to
// the "advertiser" edge. The optional arguments are used to configure the query builder of the edge.
func (msq *MlScoreQuery) WithAdvertiser(opts ...func(*AdvertiserQuery)) *MlScoreQuery {
	query := (&AdvertiserClient{config: msq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	msq.withAdvertiser = query
	return msq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MlScore.Query().
//		GroupBy(mlscore.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MlScoreQuery) GroupBy(field string, fields ...string) *MlScoreGroupBy {
	msq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MlScoreGroupBy{build: msq}
	grbuild.flds = &msq.ctx.Fields
	grbuild.label = mlscore.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.MlScore.Query().
//		Select(mlscore.FieldUserID).
//		Scan(ctx, &v)
func (msq *MlScoreQuery) Select(fields ...string) *MlScoreSelect {
	msq.ctx.Fields = append(msq.ctx.Fields, fields...)
	sbuild := &MlScoreSelect{MlScoreQuery: msq}
	sbuild.label = mlscore.Label
	sbuild.flds, sbuild.scan = &msq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MlScoreSelect configured with the given aggregations.
func (msq *MlScoreQuery) Aggregate(fns ...AggregateFunc) *MlScoreSelect {
	return msq.Select().Aggregate(fns...)
}

func (msq *MlScoreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range msq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, msq); err != nil {
				return err
			}
		}
	}
	for _, f := range msq.ctx.Fields {
		if !mlscore.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MlScoreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MlScore, error) {
	var (
		nodes       = []*MlScore{}
		_spec       = msq.querySpec()
		loadedTypes = [2]bool{
			msq.withUser != nil,
			msq.withAdvertiser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MlScore).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MlScore{config: msq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := msq.withUser; query != nil {
		if err := msq.loadUser(ctx, query, nodes, nil,
			func(n *MlScore, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := msq.withAdvertiser; query != nil {
		if err := msq.loadAdvertiser(ctx, query, nodes, nil,
			func(n *MlScore, e *Advertiser) { n.Edges.Advertiser = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (msq *MlScoreQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*MlScore, init func(*MlScore), assign func(*MlScore, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MlScore)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (msq *MlScoreQuery) loadAdvertiser(ctx context.Context, query *AdvertiserQuery, nodes []*MlScore, init func(*MlScore), assign func(*MlScore, *Advertiser)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*MlScore)
	for i := range nodes {
		fk := nodes[i].AdvertiserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(advertiser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "advertiser_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (msq *MlScoreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.ctx.Fields
	if len(msq.ctx.Fields) > 0 {
		_spec.Unique = msq.ctx.Unique != nil && *msq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MlScoreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mlscore.Table, mlscore.Columns, sqlgraph.NewFieldSpec(mlscore.FieldID, field.TypeInt))
	_spec.From = msq.sql
	if unique := msq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if msq.path != nil {
		_spec.Unique = true
	}
	if fields := msq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mlscore.FieldID)
		for i := range fields {
			if fields[i] != mlscore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if msq.withUser != nil {
			_spec.Node.AddColumnOnce(mlscore.FieldUserID)
		}
		if msq.withAdvertiser != nil {
			_spec.Node.AddColumnOnce(mlscore.FieldAdvertiserID)
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MlScoreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(mlscore.Table)
	columns := msq.ctx.Fields
	if len(columns) == 0 {
		columns = mlscore.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.ctx.Unique != nil && *msq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MlScoreGroupBy is the group-by builder for MlScore entities.
type MlScoreGroupBy struct {
	selector
	build *MlScoreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MlScoreGroupBy) Aggregate(fns ...AggregateFunc) *MlScoreGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the selector query and scans the result into the given value.
func (msgb *MlScoreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, msgb.build.ctx, ent.OpQueryGroupBy)
	if err := msgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MlScoreQuery, *MlScoreGroupBy](ctx, msgb.build, msgb, msgb.build.inters, v)
}

func (msgb *MlScoreGroupBy) sqlScan(ctx context.Context, root *MlScoreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*msgb.flds)+len(msgb.fns))
		for _, f := range *msgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*msgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MlScoreSelect is the builder for selecting fields of MlScore entities.
type MlScoreSelect struct {
	*MlScoreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mss *MlScoreSelect) Aggregate(fns ...AggregateFunc) *MlScoreSelect {
	mss.fns = append(mss.fns, fns...)
	return mss
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MlScoreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mss.ctx, ent.OpQuerySelect)
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MlScoreQuery, *MlScoreSelect](ctx, mss.MlScoreQuery, mss, mss.inters, v)
}

func (mss *MlScoreSelect) sqlScan(ctx context.Context, root *MlScoreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mss.fns))
	for _, fn := range mss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
